"""add nome_documento field to preventivi

Revision ID: 18bc99b23942
Revises: c32d5f2366b7
Create Date: 2025-05-24 19:19:35.022404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bc99b23942'
down_revision: Union[str, None] = 'c32d5f2366b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preventivi', sa.Column('nome_documento', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preventivi', 'nome_documento')
    # ### end Alembic commands ###
