"""add_cartelle_table_and_preventivo_cartella_relation

Revision ID: c32d5f2366b7
Revises: 5546c88458bf
Create Date: 2025-05-24 17:30:10.331304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32d5f2366b7'
down_revision: Union[str, None] = '5546c88458bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartelle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('icona', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cartelle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartelle_id'), 'cartelle', ['id'], unique=False)
    op.add_column('preventivi', sa.Column('cartella_id', sa.UUID(), nullable=True))
    op.alter_column('preventivi', 'stato_record',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'attivo'::character varying"))
    op.create_foreign_key(None, 'preventivi', 'cartelle', ['cartella_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preventivi', type_='foreignkey')
    op.alter_column('preventivi', 'stato_record',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'attivo'::character varying"))
    op.drop_column('preventivi', 'cartella_id')
    op.drop_index(op.f('ix_cartelle_id'), table_name='cartelle')
    op.drop_table('cartelle')
    # ### end Alembic commands ###
